
- name: Install proftpd related system packages
  apt: pkg={{ item }} state={{ galaxy_extras_apt_package_state }}
  with_items:
    - proftpd
    - proftpd-mod-pgsql
  when: galaxy_extras_install_packages

- name: Create Galaxy configuration file
  template: src=proftpd.conf.j2 dest={{ proftpd_conf_path }}

- name: Load Proftpd modules
  lineinfile: dest=/etc/proftpd/modules.conf line="{{ item }}"
  with_items:
    - LoadModule mod_sql.c
    - LoadModule mod_sql_passwd.c
    - LoadModule mod_sql_postgres.c

- name: Load Proftpd SFTP modules
  lineinfile: dest=/etc/proftpd/modules.conf line="{{ item }}"
  with_items:
    - LoadModule mod_sftp.c
    - LoadModule mod_sftp_pam.c
    - LoadModule mod_sftp_sql.c
  when: proftpd_use_sftp

- name: Install OpenSSH client package
  apt: pkg=openssh-client
  when: proftpd_use_sftp and galaxy_extras_install_packages

- name: Create /etc/proftpd/ssh_host_keys/ directory
  file: path=/etc/proftpd/ssh_host_keys/ state=directory
  when: proftpd_use_sftp

- name: Generate new SSH keys (rsa)
  shell: ssh-keygen -b 2048 -t rsa -f /etc/proftpd/ssh_host_keys/rsa -N ""
  args:
    creates: /etc/proftpd/ssh_host_keys/rsa
  when: proftpd_use_sftp

- name: Generate new SSH keys (dsa)
  shell: ssh-keygen -b 1024 -t dsa -f /etc/proftpd/ssh_host_keys/dsa -N ""
  args:
    creates: /etc/proftpd/ssh_host_keys/dsa
  when: proftpd_use_sftp

# Proftpd ships with default keys, and it makes sense to change them.
# But we've decided not to do this, because this task takes nearly a day.
# - name: Generate new DHparams
#   shell:   openssl dhparam -outform PEM {{ item[0] }} {{ item[1] }} | tee -a "${THIS_DIR}/dhparams.pem"
#   with_nested:
#     - [2, 5]
#     - [1024, 1536, 2048, 4096, 6144, 8192]
#   when: proftpd_use_sftp



