version: '3'
services:
  galaxy-server:
    image: ${IMAGE_DOMAIN:-andreassko}/galaxy-server:${IMAGE_TAG:-latest}
    build: galaxy-server
    environment:
      - GALAXY_DEFAULT_ADMIN_USER=admin
      - GALAXY_DEFAULT_ADMIN_EMAIL=admin@galaxy.org
      - GALAXY_DEFAULT_ADMIN_PASSWORD=password
      - GALAXY_DEFAULT_ADMIN_KEY=admin
    hostname: galaxy-server
    privileged: True
    ports:
      - 5555:5555
    volumes:
      # This is the directory where all your files from Galaxy will be stored
      # on your host system
      - ${EXPORT_DIR:-./export}/:/export/:delegated
      - /var/run/docker.sock:/var/run/docker.sock # TODO
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - galaxy
  galaxy-configurator:
    image: ${IMAGE_DOMAIN:-andreassko}/galaxy-configurator:${IMAGE_TAG:-latest}
    build: galaxy-configurator
    environment:
      - GALAXY_OVERWRITE_CONFIG=true
      - GALAXY_CONFIG_ADMIN_USERS=admin@galaxy.org
      - GALAXY_CONFIG_DATABASE_CONNECTION=postgresql://galaxy:chaopagoosaequuashie@postgres/galaxy
      - GALAXY_CONFIG_GALAXY_INFRASTRUCTURE_URL=http://localhost
      - GALAXY_CONFIG_CONDA_AUTO_INSTALL=true
      - GALAXY_AMQP_INTERNAL_CONNECTION=amqp://galaxy:vaiJa3ieghai2ief0jao@rabbitmq/galaxy
    volumes:
      - ${EXPORT_DIR:-./export}/galaxy/config:/galaxy/config
      - ./base_config.yml:/base_config.yml
  postgres:
    # If you are using the official postgres image, it needs to be populated by calling
    # docker-compose run galaxy install_db.sh
    # on first run
    image: ${IMAGE_DOMAIN:-andreassko}/galaxy-postgres:${IMAGE_TAG:-latest}
    build: galaxy-postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=chaopagoosaequuashie
      - POSTGRES_USER=galaxy
      - POSTGRES_DB=galaxy
    volumes:
      - ${EXPORT_DIR:-./export}/postgres/:/var/lib/postgresql/data:delegated
    networks:
      - galaxy
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - ./static_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${EXPORT_DIR:-./export}/galaxy/static:/export/galaxy/static:ro
      - ${EXPORT_DIR:-./export}/galaxy/config/plugins:/galaxy/config/plugins:ro
    depends_on:
      - galaxy-server
    networks:
      - galaxy
  # Message queue for better performance
  rabbitmq:
    image: rabbitmq:alpine
    container_name: galaxy-rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=galaxy
      - RABBITMQ_DEFAULT_PASS=vaiJa3ieghai2ief0jao
      - RABBITMQ_DEFAULT_VHOST=galaxy
    volumes:
      - ${EXPORT_DIR:-./export}/rabbitmq:/var/lib/rabbitmq:delegated
    networks:
      - galaxy
networks:
  galaxy:
