# Extend Galaxy to run jobs using Slurm.
# Example: `docker-compose -f docker-compose.yml -f docker-compose.slurm.yml up`
version: "3.7"
services:
  galaxy-configurator:
    environment:
      - GALAXY_JOB_RUNNER=slurm
      - SLURM_OVERWRITE_CONFIG=true
      - SLURM_NODE_COUNT=${SLURM_NODE_COUNT:-1}
      - SLURM_NODE_HOSTNAME=compose_slurm_node
    volumes:
      - ${EXPORT_DIR:-./export}/slurm_config:/etc/slurm-llnl
  galaxy-server:
    volumes:
      - ${EXPORT_DIR:-./export}/munge:/etc/munge
      - ${EXPORT_DIR:-./export}/slurm_config:/etc/slurm-llnl
  slurmctld:
    image: ${DOCKER_REGISTRY:-quay.io}/${DOCKER_REGISTRY_USERNAME:-bgruening}/galaxy-slurm:${IMAGE_TAG:-latest}
    build: galaxy-slurm
    command: ["slurmctld"]
    hostname: slurmctld
    volumes:
      - ${EXPORT_DIR:-./export}/slurm_config:/etc/slurm-llnl
      - ${EXPORT_DIR:-./export}/munge:/etc/munge
    networks:
      - galaxy
  slurm_node_discovery:
    image: ${DOCKER_REGISTRY:-quay.io}/${DOCKER_REGISTRY_USERNAME:-bgruening}/galaxy-slurm-node-discovery:${IMAGE_TAG:-latest}
    build: galaxy-slurm-node-discovery
    volumes:
      - ${EXPORT_DIR:-./export}/slurm_config:/etc/slurm-llnl
      - /var/run/docker.sock:/var/run/docker.sock
  slurm_node:
    image: ${DOCKER_REGISTRY:-quay.io}/${DOCKER_REGISTRY_USERNAME:-bgruening}/galaxy-slurm:${IMAGE_TAG:-latest}
    build: galaxy-slurm
    command: ["slurmd"]
    privileged: true
    labels:
      slurm_node: true
    volumes:
      - ${EXPORT_DIR:-./export}/galaxy/database:/galaxy/database
      - ${EXPORT_DIR:-./export}/galaxy/tools:/galaxy/tools:ro
      - ${EXPORT_DIR:-./export}/galaxy/lib/galaxy/tools:/galaxy/lib/galaxy/tools:ro
      - ${EXPORT_DIR:-./export}/galaxy/tool-data:/galaxy/tool-data
      - ${EXPORT_DIR:-./export}/galaxy/.venv:/galaxy/.venv
      - ${EXPORT_DIR:-./export}/tool_deps:/tool_deps
      - ${EXPORT_DIR:-./export}/slurm_config:/etc/slurm-llnl
      - ${EXPORT_DIR:-./export}/munge:/etc/munge
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - galaxy
