# Extend Galaxy to run jobs using HTCondor.
# Example: `docker-compose -f docker-compose.yml -f docker-compose.htcondor.yml up`
version: "3.7"
services:
  galaxy-configurator:
    environment:
      - GALAXY_JOB_RUNNER=condor
      - HTCONDOR_OVERWRITE_CONFIG=true
    volumes:
      - ${EXPORT_DIR:-./export}/htcondor:/htcondor
  htcondor-master:
    image: ${DOCKER_REGISTRY:-quay.io}/${DOCKER_REGISTRY_USERNAME:-bgruening}/galaxy-htcondor:${IMAGE_TAG:-latest}
    build: galaxy-htcondor
    hostname: htcondor-master
    environment:
      - HTCONDOR_TYPE=master
    volumes:
      - ${EXPORT_DIR:-./export}/htcondor:/config
    networks:
      - galaxy
  htcondor-executor:
    image: ${DOCKER_REGISTRY:-quay.io}/${DOCKER_REGISTRY_USERNAME:-bgruening}/galaxy-htcondor:${IMAGE_TAG:-latest}
    build: galaxy-htcondor
    privileged: true
    environment:
      - HTCONDOR_TYPE=executor
      - CONDOR_HOST=htcondor-master
    volumes:
      - ${EXPORT_DIR:-./export}/htcondor:/config
      - ${EXPORT_DIR:-./export}/galaxy/database:/galaxy/database
      - ${EXPORT_DIR:-./export}/galaxy/lib/galaxy/tools:/galaxy/lib/galaxy/tools:ro
      - ${EXPORT_DIR:-./export}/galaxy/tools:/galaxy/tools:ro
      - ${EXPORT_DIR:-./export}/galaxy/tool-data:/galaxy/tool-data
      - ${EXPORT_DIR:-./export}/galaxy/.venv:/galaxy/.venv
      - ${EXPORT_DIR:-./export}/tool_deps:/tool_deps
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - galaxy
  galaxy-server:
    volumes:
      - ${EXPORT_DIR:-./export}/htcondor:/htcondor_config
