# Extend Galaxy to run jobs using Pulsar. With this setup, you
# don't need to share the `/galaxy/database` path with Galaxy.
# Galaxy will send all the needed files for Pulsar, and Pulsar
# will handle the rest locally on its side.
# This docker-compose file enables for Galaxy and Pulsar to
# communicate over HTTP. To enable the MQ, concatinate the
# docker-compose.pulsar.mq.yml after this one.
# Example: `docker-compose -f docker-compose.yml -f docker-compose.pulsar.yml up`
version: "3"
services:
  galaxy-configurator:
    environment:
      - GALAXY_JOB_RUNNER=pulsar_rest
      - GALAXY_PULSAR_TRANSPORT=${GALAXY_PULSAR_TRANSPORT:-curl}
      - PULSAR_OVERWRITE_CONFIG=true
      - PULSAR_JOB_RUNNER=local
      - PULSAR_CONFIG_PRIVATE_TOKEN=changemeinproduction
      - GALAXY_PULSAR_URL=http://pulsar:8913
    volumes:
      - ${EXPORT_DIR:-./export}/pulsar/config:/pulsar/config
  pulsar:
    image: ${DOCKER_REGISTRY:-quay.io}/${DOCKER_REGISTRY_USERNAME:-bgruening}/pulsar:${IMAGE_TAG:-latest}
    build: pulsar
    hostname: pulsar
    privileged: true
    volumes:
      - ${EXPORT_DIR:-./export}/pulsar/config:/pulsar/config
      - ${EXPORT_DIR:-./export}/pulsar/dependencies:/pulsar/dependencies
    networks:
      - galaxy
